name: Update Supplier Data

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes)'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run supplier data update
      run: |
        cd scripts
        if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
          python update_supplier_data.py --dry-run --verbose
        else
          python update_supplier_data.py --verbose
        fi
    
    - name: Commit and push changes
      if: github.event.inputs.dry_run != 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated supplier data update - $(date -u +%Y-%m-%d)"
          git push
        fi
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Supplier Data Update Failed',
            body: `The automated supplier data update failed on ${new Date().toISOString()}.
            
            Please check the workflow logs for details: ${context.payload.repository.html_url}/actions/runs/${context.runId}`,
            labels: ['automation', 'bug']
          })
